blank_issues_enabled: true
contact_links:  
  - name: ❓ Question
    url: https://github.com/gerardog/gsudo/discussions/new
    about: Have a question on something? Start a new discussion thread.
  - name: 🔎 Search previous issues
    url: https://github.com/gerardog/gsudo/issues
    about: Please check if your issue has already been reported.
